services:
  database:
    container_name: database
    image: mysql:8
    environment:
      MYSQL_DATABASE: boxlang
      MYSQL_ROOT_PASSWORD: boxlang
      MYSQL_HOST: database
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - ./.db_data:/var/lib/mysql
      - ./.db_backup:/docker-entrypoint-initdb.d
    networks:
      - dev_network

  web:
    container_name: web
    build: .
    ports:
      - "8080:8080"
      - "8888:8888"
      - "8443:8443"
    volumes:
      - ./:/app
    environment:
      - BOXLANG_PORT=8080
      - BOXLANG_HOST=0.0.0.0
      - BOXLANG_DEBUG=true
      - BOXLANG_MODULES=bx-compat,bx-esapi,bx-mysql
    depends_on:
      - database
    networks:
      - dev_network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8181:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/www/public
    depends_on:
      - web
    networks:
      - dev_network
networks:
  dev_network:
    driver: bridge
