services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "8888:8888"
      - "8443:8443"
    volumes:
      - ./:/app
    environment:
      - BOXLANG_PORT=8080
      - BOXLANG_HOST=0.0.0.0
      - BOXLANG_DEBUG=true
      - BOXLANG_MODULES=bx-compat,bx-esapi,bx-mysql

  mysql:
    platform: linux/x86_64 # Needed for Mac's on the M1 chip
    image: mysql:5
    environment:
      MYSQL_DATABASE: boxlang
      MYSQL_ROOT_PASSWORD: boxlang
    ports:
      - "3306:3306"
    volumes:
      - ./.db_data:/var/lib/mysql
      - ./.db_backup:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/www/public
    depends_on:
      - web
      - mysql



